### ISSUE TITLE
is it possible to get android port of this?

### ISSUE THREAD

**Issue by GeorvityLabs** [FeiGeChuanShu/GFPGAN-ncnn#1]
could this work on android , inference on android device?

**Comment by GeorvityLabs** [comment]
maybe GFPGAN on video as well?

**Comment by FeiGeChuanShu** [comment]
@GeorvityLabs the model is too large to work on android, a lite model is needed.

**Comment by GeorvityLabs** [comment]
I see. I've tested it on Colab , yup , might take a while before the lite model is made.

**Comment by GeorvityLabs** [comment]
@FeiGeChuanShu Can you make a colab notebook of this , maybe GFPGAN for video ?

**Comment by umitkacar** [comment]
Can you share the model weights? I could not download them because of the [Baidu Pan](https://pan.baidu.com/s/1zbVwK7kh6uVfWgq9AZDJDA) link.
