### ISSUE TITLE
Can not link target, missing file ncnn.lib

### ISSUE THREAD

**Issue by Sg4Dylan** [FeiGeChuanShu/GFPGAN-ncnn#2]
OS: Windows 10 21H1
Build tool: Visual Studio 2019

Commands: 
```
mkdir build
cd build
cmake ..
cmake --build .
```

Result:
```
LINK : fatal error LNK1104: 无法打开文件“ncnn.lib” [D:\GFPGAN-ncnn\build\ncnn_gfpgan.vcxproj]
```

**Comment by FeiGeChuanShu** [comment]
自己用最新的ncnn代码编译一个即可

**Comment by Sg4Dylan** [comment]
换成源码，用 nmake 编译可以了

**Comment by umitkacar** [comment]
Can you share the model weights? I could not download them because of the [Baidu Pan](https://pan.baidu.com/s/1zbVwK7kh6uVfWgq9AZDJDA) link.
